[hooks]
pre-commit = "cargo sync-readme && git add README.md"
pre-push = """\
    cargo fmt -- --check \
    && cargo test \
    && cargo clippy -- -D warnings \
    && cargo sync-readme -c \
    """

[logging]
verbose = true
